### ISSUE TITLE
가온누리 팀 배리어프리 로고 만들기

### ISSUE THREAD

**Issue by yansigit** [gaonbarrier/gaonbarrier.github.io#1]
일단 임시로 구글링해서 다른 단체 로고 끼워놔서...
빠르게 새로 만들어야 할듯

**Comment by Seulgi98** [comment]
저희 동아리 뜻이 뭐였나요?? 아시는분??
아니면 뜻 상관없이 아무 마크나 필요한거면 대충 만들어올수는 있습니다

**Comment by yansigit** [comment]
@yansigit 저번에 우진이가 회장한테 물어봤는데 대답 왔는지 모르겠네
이미지파일 여기에도 올려줘!

**Comment by Seulgi98** [comment]
#
![가온누리 마크4](https://user-images.githubusercontent.com/68500858/87914581-cd408f00-caab-11ea-8d70-c00e0b07ef72.png)
예시 1 : 개발팀 강조, 세상 강조한 깔끔한 로고

#
![가온누리 마크3](https://user-images.githubusercontent.com/68500858/87914634-e6494000-caab-11ea-8cf2-cef117a45127.png)
예시 2 : 원 대신 지구로 세상 강조, 색상 (정직을 뜻하는 파랑, 세상을 뜻하는 초록) 포인트 줌 (글씨위치, 글씨체 수정가능)

#
![가온누리 마크1](https://user-images.githubusercontent.com/68500858/87914691-fc570080-caab-11ea-9d0a-2c4a2d36c160.png)
예시 3 : 그룹을 뜻하는 원과 색상 (정직을 뜻하는 파랑, 세상을 뜻하는 초록)

**Comment by yansigit** [comment]
디자인 변경했으므로 해당 이슈 종료합니다
